version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: localhost
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  service-contact:
    build: ./contact
    container_name: service-contact
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/contact
      spring.datasource.username: root
      spring.datasource.password: 
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8086:8085"
    links:
      - mysqldb

  service-education:
    build: ./educ
    container_name: service-education
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/education
      spring.datasource.username: root
      spring.datasource.password: 
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8084:8084"
    links:
      - mysqldb

  service-experience:
    build: ./experience
    container_name: service-experience
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/experience
      spring.datasource.username: root
      spring.datasource.password: 
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8083:8083"
    links:
      - mysqldb

  service-project:
    build: ./project
    container_name: service-project
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/project
      spring.datasource.username: root
      spring.datasource.password: 
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8082:8082"
    links:
      - mysqldb

  service-skill:
    build: ./skills
    container_name: service-skill
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/skill
      spring.datasource.username: root
      spring.datasource.password: 
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8081:8081"
    links:
      - mysqldb

  eurekaserver:
    container_name: eurekaserver
    build: ./server_eureka
    ports:
      - "8762:8761"

  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "8888:8888"
    environment:
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    links:
      - eurekaserver
      - service-skill
      - service-project
      - service-experience
      - service-education
      - service-contact

  reactapp:
    build: ./front-main
    container_name: front-app
    restart: always
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
