sonar.projectKey=mikaliqualite_educ
sonar.sources=.
sonar.login=075d4dc8e7e0d91d1c1d124fcca7bc989081c3c6
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target\classes\com\education\controller
sonar.host.url=https://sonarcloud.io
sonar.organization=mikaliqualite