server:
  port: 8082

spring:
  application:
    name: SERVICE-PROJECT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?createDatabaseIfNotExist=true
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true